# FROM ubuntu:18.04
FROM centos:7

MAINTAINER luksi1

ARG FOREMAN_RELEASE

# ENV DEBIAN_FRONTEND=noninteractive \
#     TZ=Europe/Stockholm \
#     # Gosu version. Gosu is used to run applications using a specific user.
#     GOSU_VERSION=1.9

# Install gosuENV GOSU_VERSION 1.9
# RUN set -x \
#    && apt-get update && apt-get install -y --no-install-recommends ca-certificates wget tzdata locales nscd \
#    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" \
#    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" \
#    && export GNUPGHOME="$(mktemp -d)" \
#    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
#    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
#    && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
#    && chmod +x /usr/local/bin/gosu \
#    && gosu nobody true

# RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates wget tzdata locales gnupg

# Enable en_US.utf8 for Foreman
# See: http://projects.theforeman.org/issues/13496
# RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
#     echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
#     dpkg-reconfigure --frontend=noninteractive locales && \
#     update-locale LANG=en_US.UTF-8

# Enable Puppet repo
# This is simply done here to speed up the foreman-installer
# RUN wget https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
# RUN dpkg -i puppetlabs-release-pc1-xenial.deb
# RUN rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
# RUN yum localinstall -y https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
RUN yum localinstall -y https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm

# Puppet needs UID/GID 999 as this is used as standard
# in puppet-in-docker containers
# RUN groupadd -g 999 puppet
# RUN useradd -ms /bin/bash -g puppet -u 999 puppet

# Foreman Puppet run is built for RedHat. Add /var/www directory for use with Ubuntu
# RUN mkdir /var/www

# Install Foreman repository
RUN yum localinstall -y https://yum.theforeman.org/releases/$FOREMAN_RELEASE/el7/x86_64/foreman-release.rpm
RUN yum install -y centos-release-scl-rh
RUN yum install -y epel-release
RUN yum install -y foreman-release-scl
# Enable Foreman repo
# RUN echo deb http://deb.theforeman.org/ bionic $FOREMAN_RELEASE > /etc/apt/sources.list.d/foreman.list && \
#     echo deb http://deb.theforeman.org/ plugins $FOREMAN_RELEASE >> /etc/apt/sources.list.d/foreman.list && \
#     wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add - 

# RUN yum install -y puppet-agent foreman-installer foreman-postgresql puppet-agent-oauth foreman-proxy foreman-cli apache2
RUN yum install -y foreman-rake foreman-installer foreman-postgresql mailcap httpd puppet-agent mod-ssl mod_passenger

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 443
VOLUME /etc/puppetlabs/puppet/ssl/
