FROM postgres:9.6

# copied from
# https://github.com/puppetlabs/puppet-in-docker/blob/5.3.2-updates/puppetdb-postgres/Dockerfile
MAINTAINER Luke Simmons (luksi1)

COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
COPY Dockerfile /

